env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:json/recommended'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
  - json
settings:
  react:
    version: detect
ignorePatterns: ['electron/*.js', 'build', 'dist', 'purgecss.js', 'tests']
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  no-console:
    - error
  no-alert:
    - error
  no-template-curly-in-string:
    - error
  array-callback-return:
    - error
  block-scoped-var:
    - error
  class-methods-use-this:
    - error
  curly:
    - error
    - multi-line
    - consistent
  consistent-return:
    - error
  dot-notation:
    - error
  dot-location:
    - error
    - property
  eqeqeq:
    - error
    - smart
  no-else-return:
    - error
  no-extra-bind:
    - error
  no-eval:
    - error
  no-floating-decimal:
    - error
  no-implicit-globals:
    - error
  no-invalid-this:
    - error
  no-multi-spaces:
    - error
  no-shadow:
    - error
    - builtinGlobals: false
      hoist: all
  no-use-before-define:
    - error
  prettier/prettier:
    - error
  react/prop-types:
    - off
  template-curly-spacing:
    - error
    - never
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  space-infix-ops:
    - error
  space-in-parens:
    - error
    - never
  space-before-function-paren:
    - error
    - named: never
      anonymous: always
      asyncArrow: always
  space-before-blocks:
    - error
    - always
  semi-style:
    - error
    - last
  semi-spacing:
    - error
    - before: false
      after: true
  rest-spread-spacing:
    - error
    - never
  react/react-in-jsx-scope:
    - off
  padding-line-between-statements:
    # add more rules
    - error
    - blankLine: always
      prev: '*'
      next: import
    - blankLine: any
      prev: import
      next: import
  padded-blocks:
    - error
    - never
  operator-linebreak:
    - error
    - after
    - overrides:
        ?: before
        :: before
  object-curly-spacing:
    - error
    - always
  object-curly-newline:
    - error
    - consistent: true
  nonblock-statement-body-position:
    - error
    - beside
  no-whitespace-before-property:
    - error
  no-trailing-spaces:
    - error
  no-multiple-empty-lines:
    - error
  max-len:
    - error
    - ignoreStrings: true
      ignoreRegExpLiterals: true
      ignoreTemplateLiterals: true
  keyword-spacing:
    - error
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  jsx-quotes:
    - error
    - prefer-double
  implicit-arrow-linebreak:
    - error
    - beside
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
    - consistent
  func-call-spacing:
    - error
    - never
  eol-last:
    - error
    - always
  computed-property-spacing:
    - error
    - never
  comma-style:
    - error
    - last
  comma-spacing:
    - error
    - before: false
      after: true
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: false
  block-spacing:
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  arrow-parens:
    - error
    - always
  array-element-newline:
    - error
    - consistent
  array-bracket-spacing:
    - error
    - never
  array-bracket-newline:
    - error
    - consistent
  spaced-comment:
    - error
    - always
  require-await:
    - error
  quote-props:
    - error
    - as-needed
  prefer-template:
    - error
  prefer-rest-params:
    - error
  prefer-object-spread:
    - error
  prefer-destructuring:
    - error
    - array: true
      object: true
  prefer-const:
    - error
  prefer-arrow-callback:
    - error
  object-shorthand:
    - error
    - always
  no-var:
    - error
  no-useless-return:
    - error
  no-useless-rename:
    - error
  no-return-await:
    - error
  no-return-assign:
    - error
    - except-parens
  no-param-reassign:
    - error
  no-nested-ternary:
    - error
  no-negated-condition:
    - error
  no-multi-assign:
    - error
  no-magic-numbers:
    - error
    - enforceConst: true
      ignoreArrayIndexes: true
  no-global-assign:
    - error
  no-extra-semi:
    - error
  no-empty-function:
    - error
  no-confusing-arrow:
    - error
  no-array-constructor:
    - error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
overrides:
  - files:
      - src/**
    env:
      browser: true
      es2021: true
  - files:
      - dev/**
    env:
      node: true
      es2021: true
