printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
endOfLine: lf
bracketSameLine: false
arrowParens: always
quoteProps: as-needed
jsxSingleQuote: false
